### ISSUE TITLE
curl command on github pages returns html

### ISSUE THREAD

**Issue by sethwoodworth** [denilsonsa/prettyping#10]
curl -O https://github.com/denilsonsa/prettyping/raw/master/prettyping

returns 

    <html><body>You are being <a href="https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping">redirected</a>.</body></html>

What you want is:

    curl -O https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping

**Comment by denilsonsa** [comment]
Thanks! Fixed by #2.
