### ISSUE TITLE
Numbers in legend further from reference bar than next

### ISSUE THREAD

**Issue by scraperdragon** [denilsonsa/prettyping#6]
The small (<100) numbers in the legend are right aligned; they should be left-aligned to be closer to their bar.

e.g. in it looks like 30 is referring to the bar on its right, not the bar on its left, which is further away due to a space.

![](http://snag.gy/V4dn5.jpg)
[deliberately misleadingly cropped]

**Comment by denilsonsa** [comment]
I think the commit e8d7538b8742b27cffe28e9dfe13d1d1a12288e3 solves this issue. I'm closing this now. Sorry for taking too long, and feel free to contribute with more feedback!
